# Workflow file for fast unit tests which run on all commits
name: Unit tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
      - uses: chartboost/ruff-action@v1
        with:
          args: 'format --check'
          
  unit-tests:
    name: Unit tests
    needs: ruff  # avoid wasting CI time if static analysis failed
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13]
    
    steps:
      - uses: actions/checkout@v4      
      - name: Set up Conda environment from environment.yaml
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yaml
          auto-activate-base: false
      - name: Install RasCAL2
        run: pip install .
      - name: Run pytest
        run: pytest -s tests/ -m "not slow" --cov=rascal2 --cov-report=term
